import type { Lodging, Food, Event } from "@/types";

export const mockLodging: Lodging[] = [
  {
    id: "lodging-1",
    name: "Al-Ahsa InterContinental",
    nameAr: "فندق انتركونتيننتال الأحساء",
    type: "hotel",
    city: "Al-Hofuf",
    cityAr: "الهفوف",
    neighborhood: "Al-Ahsa",
    neighborhoodAr: "الأحساء",
    priceRange: "450-650 SAR",
    rating: 4.7,
    images: ["https://pub-d7fc967a0d9e4e42bba0d712e4f9b96e.r2.dev/lodging/intercontinental-aea218dd.webp"],
    amenities: ["Wi-Fi", "Pool", "Spa", "Date Palm Gardens", "Traditional Dining", "Prayer Room"],
    amenitiesAr: ["واي فاي", "مسبح", "سبا", "حدائق النخيل", "مطعم تراثي", "مصلى"],
    description: "Luxury hotel in the heart of Al-Ahsa Oasis with views of ancient date palm groves and traditional architecture.",
    descriptionAr: "فندق فاخر في قلب واحة الأحساء مع إطلالات على بساتين النخيل القديمة والعمارة التراثية.",
  },
  {
    id: "lodging-2",
    name: "Kayan Al Bustan Apartments",
    nameAr: "شقق كيان البستان",
    type: "apartment",
    city: "Al-Hofuf",
    cityAr: "الهفوف",
    neighborhood: "Al-Ahsa",
    neighborhoodAr: "الأحساء",
    priceRange: "300-450 SAR",
    rating: 4.8,
    images: ["https://pub-d7fc967a0d9e4e42bba0d712e4f9b96e.r2.dev/lodging/kayan-apartments-f7de2915.jpg"],
    amenities: ["Wi-Fi", "Traditional Kitchen", "Parking", "Mountain Views", "Prayer Room", "Date Garden Access"],
    amenitiesAr: ["واي فاي", "مطبخ تراثي", "موقف سيارات", "إطلالة الجبل", "مصلى", "حديقة النخيل"],
    description: "Authentic Al-Ahsa apartment near Jabal Al-Qara caves with traditional Hasawi architecture and oasis views.",
    descriptionAr: "شقة أصيلة في الأحساء بالقرب من كهوف جبل القارة مع العمارة الحساوية التراثية وإطلالات الواحة.",
  },
  {
    id: "lodging-3",
    name: "Al-Ahsa Desert Camp",
    nameAr: "مخيم صحراء الأحساء",
    type: "camp",
    city: "Eastern Desert",
    cityAr: "الصحراء الشرقية",
    neighborhood: "Al-Ahsa",
    neighborhoodAr: "الأحساء",
    priceRange: "800-1200 SAR",
    rating: 4.9,
    images: ["https://pub-d7fc967a0d9e4e42bba0d712e4f9b96e.r2.dev/lodging/desert-camp-a2dc07bf.jpg"],
    amenities: ["Traditional Meals", "Camel Rides", "Falconry", "Stargazing", "Bedouin Stories", "Date Harvesting"],
    amenitiesAr: ["وجبات تراثية", "ركوب الجمال", "الصقارة", "مراقبة النجوم", "قصص بدوية", "جني التمور"],
    description: "Authentic desert experience on the edge of Al-Ahsa Oasis with traditional Bedouin hospitality and date palm excursions.",
    descriptionAr: "تجربة صحراوية أصيلة على حافة واحة الأحساء مع الضيافة البدوية التراثية ورحلات بساتين النخيل.",
  },
  {
    id: "lodging-4",
    name: "Lily Palms Hotel",
    nameAr: "فندق ليلي بالمز",
    type: "hotel",
    city: "Al-Hofuf Center",
    cityAr: "وسط الهفوف",
    neighborhood: "Al-Ahsa",
    neighborhoodAr: "الأحساء",
    priceRange: "350-500 SAR",
    rating: 4.5,
    images: ["https://pub-d7fc967a0d9e4e42bba0d712e4f9b96e.r2.dev/lodging/lily-palms-0c1226df.webp"],
    amenities: ["Wi-Fi", "Oasis Views", "Pool", "Traditional Restaurant", "Prayer Room", "Spa"],
    amenitiesAr: ["واي فاي", "إطلالة الواحة", "مسبح", "مطعم تراثي", "مصلى", "سبا"],
    description: "Central hotel in Al-Hofuf with easy access to traditional souks and UNESCO World Heritage sites.",
    descriptionAr: "فندق مركزي في الهفوف مع سهولة الوصول إلى الأسواق التراثية ومواقع التراث العالمي لليونسكو.",
  },
  {
    id: "lodging-5",
    name: "Homestay Experience",
    nameAr: "تجربة الاستضافة الشعبية",
    type: "homestay",
    city: "Old Al-Hofuf",
    cityAr: "الهفوف القديمة",
    neighborhood: "Al-Ahsa",
    neighborhoodAr: "الأحساء",
    priceRange: "250-350 SAR",
    rating: 4.9,
    images: ["https://pub-d7fc967a0d9e4e42bba0d712e4f9b96e.r2.dev/lodging/homestay-1-069492f0.jpg"],
    amenities: ["Traditional Breakfast", "Arabic Coffee", "Cultural Stories", "Date Farm Tour", "Traditional Cooking Class", "Prayer Room"],
    amenitiesAr: ["فطور تراثي", "قهوة عربية", "قصص ثقافية", "جولة مزرعة التمور", "دروس الطبخ التراثي", "مصلى"],
    description: "Experience authentic Hasawi hospitality in a traditional family home with home-cooked meals and cultural experiences.",
    descriptionAr: "اختبر الضيافة الحساوية الأصيلة في بيت عائلي تقليدي مع وجبات منزلية وتجارب ثقافية.",
  },
];

export const mockFood: Food[] = [
  {
    id: "food-1",
    name: "Al-Ahsa Traditional Restaurant",
    nameAr: "مطعم الأحساء التراثي",
    category: "restaurant",
    cuisine: "Hasawi Traditional",
    cuisineAr: "حساوي تراثي",
    avgPrice: "80-150 SAR",
    hours: "12:00 PM - 11:00 PM",
    images: ["https://pub-d7fc967a0d9e4e42bba0d712e4f9b96e.r2.dev/food/traditional-restaurant-7f7a7b7f.webp"],
    description: "Authentic Hasawi cuisine featuring date-stuffed lamb, traditional rice dishes, and fresh seafood from Al-Uqair.",
    descriptionAr: "مأكولات حساوية أصيلة تتميز بالخروف المحشو بالتمر وأطباق الأرز التراثية والمأكولات البحرية الطازجة من العقير.",
    rating: 4.8,
  },
  {
    id: "food-2",
    name: "Sultanah Kitchen",
    nameAr: "مطبخ سلطانة",
    category: "home_kitchen",
    cuisine: "Home-style Hasawi",
    cuisineAr: "حساوي منزلي",
    avgPrice: "40-80 SAR",
    hours: "5:00 PM - 10:00 PM",
    images: ["https://pub-d7fc967a0d9e4e42bba0d712e4f9b96e.r2.dev/food/sultanah-kitchen-78cc88d7.jpg"],
    description: "Traditional Hasawi dishes prepared by local productive families, featuring date-based sweets and oasis vegetables.",
    descriptionAr: "أطباق حساوية تراثية محضرة من قبل الأسر المنتجة المحلية، تتميز بالحلويات المعتمدة على التمر وخضروات الواحة.",
    rating: 4.9,
  },
  {
    id: "food-3",
    name: "Al-Hofuf Dates & Sweets",
    nameAr: "تمور وحلويات الهفوف",
    category: "fastfood",
    cuisine: "Traditional Sweets",
    cuisineAr: "حلويات تراثية",
    avgPrice: "20-45 SAR",
    hours: "8:00 AM - 11:00 PM",
    images: ["https://pub-d7fc967a0d9e4e42bba0d712e4f9b96e.r2.dev/food/dates-sweets-83cdc6f1.jpg"],
    description: "Famous for Al-Ahsa dates, traditional sweets, and quick Hasawi snacks in the heart of Al-Hofuf.",
    descriptionAr: "مشهور بتمور الأحساء والحلويات التراثية والوجبات الحساوية السريعة في قلب الهفوف.",
    rating: 4.7,
  },
  {
    id: "food-4",
    name: "Qahwat Al-Ahsa",
    nameAr: "قهوة الأحساء",
    category: "drinks",
    cuisine: "Traditional Beverages",
    cuisineAr: "مشروبات تراثية",
    avgPrice: "15-35 SAR",
    hours: "5:00 AM - 12:00 AM",
    images: ["https://pub-d7fc967a0d9e4e42bba0d712e4f9b96e.r2.dev/food/qahwat-alahsa-35297790.jpg"],
    description: "Traditional Al-Ahsa coffee house serving qahwa with fresh dates, karak tea, and local hospitality.",
    descriptionAr: "مقهى تراثي في الأحساء يقدم القهوة مع التمر الطازج وشاي الكرك والضيافة المحلية.",
    rating: 4.6,
  },
  {
    id: "food-5",
    name: "Al-Uqair Seafood House",
    nameAr: "بيت العقير للمأكولات البحرية",
    category: "restaurant",
    cuisine: "Fresh Seafood",
    cuisineAr: "مأكولات بحرية طازجة",
    avgPrice: "100-180 SAR",
    hours: "12:00 PM - 11:00 PM",
    images: ["https://pub-d7fc967a0d9e4e42bba0d712e4f9b96e.r2.dev/food/uqair-seafood-d2798dbc.jpg"],
    description: "Fresh Arabian Gulf seafood from Al-Uqair port, featuring grilled hammour, shrimp, and traditional fish curry.",
    descriptionAr: "مأكولات بحرية طازجة من الخليج العربي من ميناء العقير، تتميز بالهامور المشوي والروبيان وكاري السمك التراثي.",
    rating: 4.7,
  },
];

export const mockEvents: Event[] = [
  {
    id: "event-1",
    title: "Al-Ahsa Date Festival",
    titleAr: "مهرجان تمور الأحساء",
    category: "festival",
    date: "October 15, 2024",
    time: "4:00 PM - 11:00 PM",
    location: "Al-Hofuf Date Palm Groves",
    locationAr: "بساتين نخيل الهفوف",
    images: ["https://pub-d7fc967a0d9e4e42bba0d712e4f9b96e.r2.dev/events/date-festival-0ae96b03.jpg"],
    description: "Annual celebration of Al-Ahsa's world-famous dates with tastings, traditional crafts, and cultural performances.",
    descriptionAr: "احتفال سنوي بتمور الأحساء المشهورة عالمياً مع التذوق والحرف التراثية والعروض الثقافية.",
  },
  {
    id: "event-2",
    title: "UNESCO Oasis Heritage Conference",
    titleAr: "مؤتمر تراث واحة اليونسكو",
    category: "conference",
    date: "November 20, 2024",
    time: "9:00 AM - 6:00 PM",
    location: "Al-Ahsa Cultural Center",
    locationAr: "مركز الأحساء الثقافي",
    images: ["https://pub-d7fc967a0d9e4e42bba0d712e4f9b96e.r2.dev/events/unesco-conference-3f1eea82.jpg"],
    description: "International conference on oasis conservation and sustainable agriculture in UNESCO World Heritage sites.",
    descriptionAr: "مؤتمر دولي حول حفظ الواحات والزراعة المستدامة في مواقع التراث العالمي لليونسكو.",
  },
  {
    id: "event-3",
    title: "Jabal Al-Qara Cave Exploration",
    titleAr: "استكشاف كهوف جبل القارة",
    category: "outdoor",
    date: "October 25, 2024",
    time: "8:00 AM - 5:00 PM",
    location: "Jabal Al-Qara Mountain",
    locationAr: "جبل القارة",
    images: ["https://pub-d7fc967a0d9e4e42bba0d712e4f9b96e.r2.dev/events/qara-caves-5a0f9843.jpg"],
    description: "Guided exploration of the famous Al-Qara caves with geological tours and traditional storytelling.",
    descriptionAr: "استكشاف موجه لكهوف القارة الشهيرة مع جولات جيولوجية وحكايات تراثية.",
  },
  {
    id: "event-4",
    title: "Al-Ahsa Heritage Exhibition",
    titleAr: "معرض تراث الأحساء",
    category: "indoor",
    date: "November 10, 2024",
    time: "10:00 AM - 9:00 PM",
    location: "Ibrahim Palace Museum",
    locationAr: "متحف قصر إبراهيم",
    images: ["https://pub-d7fc967a0d9e4e42bba0d712e4f9b96e.r2.dev/events/heritage-exhibition-4cab5a1c.jpg"],
    description: "Discover Al-Ahsa's rich history through artifacts, traditional crafts, and interactive displays at the historic palace.",
    descriptionAr: "اكتشف تاريخ الأحساء الغني من خلال القطع الأثرية والحرف التراثية والعروض التفاعلية في القصر التاريخي.",
  },
  {
    id: "event-5",
    title: "Al-Ahsa Traditional Crafts Fair",
    titleAr: "معرض الحرف التراثية",
    category: "seasonal",
    date: "December 15, 2024",
    time: "3:00 PM - 10:00 PM",
    location: "Al-Hofuf Traditional Souq",
    locationAr: "سوق الهفوف التراثي",
    images: ["https://pub-d7fc967a0d9e4e42bba0d712e4f9b96e.r2.dev/events/crafts-fair-ed9a6bc9.jpg"],
    description: "Traditional Hasawi crafts fair featuring pottery, weaving, date products, and local artisan demonstrations.",
    descriptionAr: "معرض الحرف الحساوية التراثية يتميز بالفخار والنسيج ومنتجات التمر وعروض الحرفيين المحليين.",
  },
];

export const featuredDestinations = [
  {
    id: "dest-1",
    name: "Al-Hofuf",
    nameAr: "الهفوف",
    subtitle: "Historic center",
    subtitleAr: "المركز التاريخي",
    image: "https://pub-d7fc967a0d9e4e42bba0d712e4f9b96e.r2.dev/lodging/intercontinental-aea218dd.webp",
    featured: true,
  },
  {
    id: "dest-2",
    name: "Jabal Al-Qara",
    nameAr: "جبل القارة",
    subtitle: "Mountain caves",
    subtitleAr: "الكهوف الجبلية",
    image: "https://pub-d7fc967a0d9e4e42bba0d712e4f9b96e.r2.dev/events/qara-caves-5a0f9843.jpg",
    featured: true,
  },
  {
    id: "dest-3",
    name: "Al-Uqair",
    nameAr: "العقير",
    subtitle: "Historic port",
    subtitleAr: "الميناء التاريخي",
    image: "https://pub-d7fc967a0d9e4e42bba0d712e4f9b96e.r2.dev/events/fishing-festival-a6fafe72.jpg",
    featured: true,
  },
  {
    id: "dest-4",
    name: "Date Palm Groves",
    nameAr: "بساتين النخيل",
    subtitle: "UNESCO heritage",
    subtitleAr: "تراث اليونسكو",
    image: "https://pub-d7fc967a0d9e4e42bba0d712e4f9b96e.r2.dev/events/date-festival-0ae96b03.jpg",
    featured: true,
  },
  {
    id: "dest-5",
    name: "Ibrahim Palace",
    nameAr: "قصر إبراهيم",
    subtitle: "Ottoman fortress",
    subtitleAr: "القلعة العثمانية",
    image: "https://pub-d7fc967a0d9e4e42bba0d712e4f9b96e.r2.dev/events/heritage-exhibition-4cab5a1c.jpg",
    featured: true,
  },
  {
    id: "dest-6",
    name: "Al-Qarah Mountain",
    nameAr: "جبل القارة",
    subtitle: "Natural wonder",
    subtitleAr: "عجيبة طبيعية",
    image: "https://pub-d7fc967a0d9e4e42bba0d712e4f9b96e.r2.dev/lodging/kayan-apartments-f7de2915.jpg",
    featured: false,
  },
  {
    id: "dest-7",
    name: "Desert Camps",
    nameAr: "المخيمات الصحراوية",
    subtitle: "Bedouin experience",
    subtitleAr: "تجربة بدوية",
    image: "https://pub-d7fc967a0d9e4e42bba0d712e4f9b96e.r2.dev/lodging/desert-camp-a2dc07bf.jpg",
    featured: false,
  },
  {
    id: "dest-8",
    name: "Traditional Souq",
    nameAr: "السوق التراثي",
    subtitle: "Shopping heritage",
    subtitleAr: "تراث التسوق",
    image: "https://pub-d7fc967a0d9e4e42bba0d712e4f9b96e.r2.dev/events/crafts-fair-ed9a6bc9.jpg",
    featured: false,
  },
  {
    id: "dest-9",
    name: "Yellow Lake",
    nameAr: "بحيرة الأصفر",
    subtitle: "Natural reserve",
    subtitleAr: "محمية طبيعية",
    image: "https://pub-d7fc967a0d9e4e42bba0d712e4f9b96e.r2.dev/food/uqair-seafood-d2798dbc.jpg",
    featured: false,
  },
  {
    id: "dest-10",
    name: "Al-Ahsa Oasis",
    nameAr: "واحة الأحساء",
    subtitle: "World's largest oasis",
    subtitleAr: "أكبر واحة في العالم",
    image: "https://pub-d7fc967a0d9e4e42bba0d712e4f9b96e.r2.dev/lodging/lily-palms-0c1226df.webp",
    featured: false,
  },
];
